---
title: 异常捕获
tags: ['学习']
categories: 学习
date: 2022-02-28
---

最近在看前端有关异常捕获相关的知识，总结一哈。

<!--more-->

### 1.错误类型

### 1.1 js 执行错误

1. SyntaxError 语法错误 在 IDE 编译时就会被发现。

   ```javascript
   const xx //const xx = ''
   ```

2. TypeError 类型错误。

   ```javascript
   let a = undefined;
   a.name;
   ```

3. ReferenceError 引用未声明的变量。

   ```javascript
   console.log(unstated);
   ```

4. RangeError 当一个值不在其所允许的范围或者集合中。

   ```javascript
   let a = [];
   a.length = -1;
   ```

#### 1.2 网络错误

1. ResourceError

   ```javascript
   new Image().src = '/remote/image/notdeinfed.png';
   ```

2. HttpError

   ```javascript
   fetch('/remote/notdefined', {});
   ```

### 2. 错误收集

#### 2.1 try/catch

个人理解，`try/catch`使用场景偏向于捕获一些可以预料的错误：

1. coding 时感觉哪里容易出错，不想影响后面代码的编译时做一个保险。
2. 对于一些比较容易出问题的场景（比如用户输入/浏览器新特性）有可能出错，提前做准备。

#### 2.2 window.onerror

#### 2.3 window.addEventListener

后面两种捕获异常的方式更偏向于捕获一些意料不到的错误。

### 3.示例

搞一个这样的 html。

为什么要把每一个错误都单独写一个 script 标签呢？因为报错会阻止后面的代码运行，所以每一个都需要一个 script 标签，这样每一个报错都会出现：

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Test page in http://test.com</title>
  </head>
  <body>
    <h1>hello world!</h1>
    <!-- 图片加载错误（资源错误） -->
    <img src="https://yun.tuia.cn/image/ttttttttt.png" />
    <h3>test error</h3>
    <script>
      const xx; // SyntaxError 语法错误
    </script>
    <script>
      let a = undefined;
      a.name; // TypeError 类型错误
    </script>
    <script>
      console.log(b); // ReferenceError 引用错误
    </script>
    <script>
      let c = [];
      c.length = -1; // RangeError 范围错误
    </script>
    <script>
      fetch('https://tuia.cn/test'); //HttpError 本质是promise error
    </script>
    <script>
      setTimeout(() => {
        const A = 1;
        A = 2;
      }, 0); // 异步错误
    </script>
  </body>
</html>
```

![AllErrorCompare](https://dqtwdd.top/cdn/img/AllErrorCompare.png)

好耶！七个错误一个不少。

然后我们分别用三种方式尝试一下错误捕获：

```html
<script>
  window.onerror = function (message, source, lineno, colno, error) {
    console.log('window.onerror捕获到异常：', {
      message,
      source,
      lineno,
      colno,
      error,
    });
  };
  window.addEventListener(
    'error',
    (error) => {
      console.log('window.addEventListener error 捕获到异常：', error.message);
    },
    true
  );
  window.addEventListener(
    'unhandledrejection',
    function (e) {
      console.log('unhandledrejection捕获到异常：', e);
    }
  );
</script>
```

`window.onerror`：

![windowOnError](https://dqtwdd.top/cdn/img/windowOnError.png)

可以看到 js 的执行错误都被捕获到了。但是`fetch`请求的错误和资源请求的错误捕获不到。

`window.addEventListener( 'error',()=>{})`:

![windowAddEventListenerError](https://dqtwdd.top/cdn/img/windowAddEventListenerError.png)

同样的，`window.addEventListener( 'error',()=>{})`可以捕获到所有 js 的执行错误，同时也可以捕获到图片的资源的错误。但是也无法捕获`fetch`的错误。

其实这两个方法都无法捕获的`fetch`错误本质其实是`promise`错误，`promise`本身没有对`reject`情况进行处理导致报错。

所以我们可以使用最后一个方法来捕获：`window.addEventListener('unhandledrejection',()=>{})`。

`window.addEventListener('unhandledrejection',()=>{})`:

稍微修改一下示例，增加一个`promise`使例子更加生动：

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Test page in http://test.com</title>
  </head>
  <body>
    <h1>hello world!</h1>
    <!-- 图片加载错误（资源错误） -->
    <img src="https://yun.tuia.cn/image/ttttttttt.png" />
    <h3>test error</h3>
    <script>
      window.addEventListener('unhandledrejection', function (e) {
        console.log('unhandledrejection捕获到异常：', e);
      });
    </script>
    <script>
      const xx; // SyntaxError 语法错误
    </script>
    <script>
      let a = undefined;
      a.name; // TypeError 类型错误
    </script>
    <script>
      console.log(b); // ReferenceError 引用错误
    </script>
    <script>
      let c = [];
      c.length = -1; // RangeError 范围错误
    </script>
    <script>
      fetch('https://666.0.0.1.cn/test'); //HttpError 本质是promise error
    </script>
    <script>
      setTimeout(() => {
        const A = 1;
        A = 2;
      }, 0); // 异步错误
    </script>
    <script>
      new Promise(function (resolve, rej) {
        console.log('promise1');
        rej('rejecttttttttttttttttt');
      }).then(function () {
        console.log('promise2'); // promise错误
      });
    </script>
  </body>
</html>
```

![promiseError](https://dqtwdd.top/cdn/img/promiseError.png)

可以看见两个`promise`未处理的错误都被捕获到了。配合`window.addEventListener( 'error',()=>{})`可以捕获到所有异常。

来个捕获异常全家福：

![AllErrorFetched](https://dqtwdd.top/cdn/img/AllErrorFetched.png)

然后就可以集中处理异常了。搞一个接口，可以把精确到哪一行报错的代码上传。

然后配置一下 wepack，在打包时将 sourcemap 打包，上传到服务器，可以实现监控前端异常。
